service: api-institutions

provider:
  name: aws
  runtime: java8
  profile: ${opt:profile, 'uvsy-dev'}
  stage: ${opt:stage, 'dev2'}
  region: ${opt:region, 'sa-east-1'}
  deploymentBucket: ${self:provider.stage}.${self:provider.region}.universy.serverless.deploys
  deploymentPrefix: ${self:provider.region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
  environment:
    STAGE: ${self:provider.stage}

plugins:
  - serverless-offline

package:
  artifact: build/distributions/${self:service}-1.0.zip


custom:

  # Database Configuration
  dbDriver: jdbc
  dbProtocol: postgresql
  dbPort: 5432
  dbName: ${self:provider.stage}-institutions
  dbHost: ${ssm:/${self:provider.stage}/${self:service}/database/host~true}
  dbUser: ${ssm:/${self:provider.stage}/${self:service}/database/user~true}
  dbPassword: ${ssm:/${self:provider.stage}/${self:service}/database/password~true}

  # Prune
  prune:
    automatic: true
    number: 3

functions:
  - ${file(./sls/functions/institutions_resource.yml)}
  - ${file(./sls/functions/careers_resource.yml)}
  - ${file(./sls/functions/programs_resource.yml)}
  - ${file(./sls/functions/subjects_resource.yml)}
  - ${file(./sls/functions/correlatives_resource.yml)}
  - ${file(./sls/functions/commissions_resource.yml)}
  - ${file(./sls/functions/courses_resource.yml)}

resources:
 - ${file(./sls/resources/courses_dynamo_db_table.yml)}

