Resources:
 CoursesTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: ${self:provider.stage}-courses
      AttributeDefinitions:
        - AttributeName: "commission_id"
          AttributeType: "S"
        - AttributeName: "subject_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "commission_id"
          KeyType: "HASH"
        - AttributeName: "subject_id"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
          - IndexName: SubjectIdIndex
            KeySchema:
              - AttributeName: subject_id
                KeyType: HASH
              - AttributeName: commission_id
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"